- hosts: all
  tasks:
  - package:
      name: "httpd"
      state: present
  
  - copy:
      content: "this is from ansible"
      dest: "/var/www/html/web.html"
  - service:
      name: "httpd"
      state: started
  - firewalld:
      port: 80/tcp
      state: enabled
      permanent: yes 
      immediate: yes
